/*
* This file is automatically generated by px_generate_mixers.py - do not edit.
*/

#ifndef _MIXER_MULTI_TABLES
#define _MIXER_MULTI_TABLES

enum class MultirotorGeometry : MultirotorGeometryUnderlyingType {
	QUAD_X,                        // Generic Quadcopter in X configuration (text key 4x)

	MAX_GEOMETRY
}; // enum class MultirotorGeometry

namespace {
static constexpr MultirotorMixer::Rotor _config_quad_x[] {
	{ -0.707107,  0.707107,  1.000000,  1.000000 },
	{  0.707107, -0.707107,  1.000000,  1.000000 },
	{  0.707107,  0.707107, -1.000000,  1.000000 },
	{ -0.707107, -0.707107, -1.000000,  1.000000 },
};

static constexpr const MultirotorMixer::Rotor *_config_index[] {
	&_config_quad_x[0],
};

static constexpr unsigned _config_rotor_count[] {
	4, /* quad_x */
};

const char* _config_key[] {
	"4x",	/* quad_x */
};

} // anonymous namespace

#endif /* _MIXER_MULTI_TABLES */

