cmake_minimum_required(VERSION 3.0.2)
project(xgc2_lightweight_sim_msgs)
find_package(catkin REQUIRED COMPONENTS message_generation)
add_service_files(FILES SetProvider.srv)
generate_messages()
catkin_package(CATKIN_DEPENDS message_runtime)
install(DIRECTORY srv DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
